# Generated by Django 5.1.6 on 2025-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_leavetype_leaveapplication_leaveapprovallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('hod', 'Hod')], max_length=20),
        ),
    ]
