# Generated by Django 5.1.6 on 2025-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='reason',
            field=models.CharField(choices=[('Casual leave', 'Casual leave'), ('Sabatical', 'Sabatical'), ('Medical', 'Approved'), ('Vacation', 'Cancelled'), ('Ma/partanity', 'Ma/partanity'), ('Bereavement', 'Bereavement'), ('Compensatory', 'Compensatory')], default='Casual leave', max_length=20, null=True),
        ),
    ]
