# Generated by Django 5.1.6 on 2025-07-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_leavetype_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Casual leave', 'Casual leave'), ('Sabatical', 'Sabatical'), ('Medical', 'Approved'), ('Vacation', 'Cancelled'), ('Ma/partanity', 'Ma/partanity'), ('Bereavement', 'Bereavement'), ('Compensatory', 'Compensatory')], default='Casual leave', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
